### ISSUE TITLE
LISTEN_PORT override doesn't work for Nginx in Python 3.7 / Alpine 3.7

### ISSUE THREAD

**Issue by FireDrunk** [tiangolo/uwsgi-nginx-docker#42] opened 2018-09-28 10:28 UTC
The nginx.conf doesn't contain a 'listen' line, so the sed -i in entrypoint.sh doesn't work.

**Comment by tiangolo** [comment] 2018-09-28 12:05
Strange, it seems to work OK here:

```bash
docker run -d --name uwsgi -p 80:8080 -e LISTEN_PORT=8080 tiangolo/uwsgi-nginx:python3.7-alpine3.7
```

then I open `http://localhost` and it shows the default content.

Or also:

```bash
docker run -d --name uwsgi -p 8080:8080 -e LISTEN_PORT=8080 tiangolo/uwsgi-nginx:python3.7-alpine3.7
```

then I open `http://localhost:8080` and it shows the default content.

---

Do you have some steps to reproduce your issue?

If you create a repo that shows how to reproduce the issue maybe I can take a look.

**Comment by tiangolo** [comment] 2019-01-11 10:54
Python 3.7 in Alpine is (temporarily) not supported. Not because I don't want to, but because there's no official `uwsgi` for Python 3.7 in Alpine: https://github.com/tiangolo/uwsgi-nginx-docker#temporarily-not-supported

For now, you can use Python 3.6 in Alpine or Python 3.7 standard (based on Debian).

I'll close this now, but feel free to re-open it, add any additional comments or create new issues.

**Closed by tiangolo** 2019-01-11 10:54 UTC
